# Generated by Django 5.0.2 on 2024-02-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_gallery', '0002_music_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(upload_to='music_picture'),
        ),
    ]
