# Generated by Django 5.0.2 on 2024-02-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_gallery', '0003_gallery_image_alter_music_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
